# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Restic-Server add-on
version: "1.2.0"
slug: Restic Server for HAOS HomeAssistant Operating System
description: Example add-on
url: "https://github.com/rnwolf/addons-rnwolf/tree/main/restic-server"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
#image: "ghcr.io/rnwolf/{arch}-addon-restic-server"
